import { Year, Competency } from "./types";

export const COMPETENCIES: Record<Year, Competency[]> = {
  [Year.FIRST]: [
    { id: "1-EC-1", category: "Etico-Comportamentale", description: "Puntualità e rispetto degli orari di tirocinio." },
    { id: "1-EC-2", category: "Etico-Comportamentale", description: "Rispetto della divisa e del decoro professionale (unghie corte e prive di smalto e capelli raccolti)." },
    { id: "1-EC-3", category: "Etico-Comportamentale", description: "Responsabilità nell'esecuzione dei compiti assegnati." },
    { id: "1-EC-4", category: "Etico-Comportamentale", description: "Rispetto del segreto professionale e della privacy." },
    { id: "1-EC-5", category: "Etico-Comportamentale", description: "Comunica tempestivamente l'eventuale assenza." },
    { id: "1-1", category: "Igiene e Comfort", description: "Esegue correttamente il rifacimento del letto occupato e non." },
    { id: "1-2", category: "Igiene e Comfort", description: "Assiste il paziente nell'igiene parziale e totale." },
    { id: "1-SRC", category: "Igiene e Comfort", description: "Sicurezza e Rischio Clinico: Applicazione rigorosa dei protocolli di sterilizzazione, smaltimento rifiuti speciali e prevenzione delle infezioni correlate all'assistenza (ICA)." },
    { id: "1-3", category: "Parametri Vitali", description: "Rileva correttamente pressione arteriosa, frequenza cardiaca e respiratoria." },
    { id: "1-4", category: "Relazione", description: "Dimostra capacità di ascolto attivo e comunicazione empatica." },
    { id: "1-5", category: "Sicurezza", description: "Applica le procedure di lavaggio delle mani e utilizzo dei DPI." },
  ],
  [Year.SECOND]: [
    { id: "2-EC-1", category: "Etico-Comportamentale", description: "Puntualità e rispetto degli orari di tirocinio." },
    { id: "2-EC-2", category: "Etico-Comportamentale", description: "Rispetto della divisa e del decoro professionale (unghie corte e prive di smalto e capelli raccolti)." },
    { id: "2-EC-3", category: "Etico-Comportamentale", description: "Responsabilità nell'esecuzione dei compiti assegnati." },
    { id: "2-EC-4", category: "Etico-Comportamentale", description: "Rispetto del segreto professionale e della privacy." },
    { id: "2-EC-5", category: "Etico-Comportamentale", description: "Comunica tempestivamente l'eventuale assenza." },
    { id: "2-1", category: "Terapia", description: "Prepara e somministra la terapia per via naturale (OS, sublinguale)." },
    { id: "2-2", category: "Terapia", description: "Esegue iniezioni intramuscolari e sottocutanee in sicurezza." },
    { id: "2-3", category: "Procedure Invasive", description: "Gestisce correttamente il cateterismo vescicale estemporaneo e a permanenza." },
    { id: "2-4", category: "Diagnostica", description: "Esegue prelievi ematici venosi rispettando la sterilità." },
    { id: "2-5", category: "Etica", description: "Integra i valori di rispetto e dignità nella cura del malato." },
  ],
  [Year.THIRD]: [
    { id: "3-EC-1", category: "Etico-Comportamentale", description: "Puntualità e rispetto degli orari di tirocinio." },
    { id: "3-EC-2", category: "Etico-Comportamentale", description: "Rispetto della divisa e del decoro professionale (unghie corte e prive di smalto e capelli raccolti)." },
    { id: "3-EC-3", category: "Etico-Comportamentale", description: "Responsabilità nell'esecuzione dei compiti assegnati." },
    { id: "3-EC-4", category: "Etico-Comportamentale", description: "Rispetto del segreto professionale e della privacy." },
    { id: "3-EC-5", category: "Etico-Comportamentale", description: "Comunica tempestivamente l'eventuale assenza." },
    { id: "3-1", category: "Emergenza", description: "Riconosce i segni di instabilità clinica e allerta il team." },
    { id: "3-2", category: "Gestione Complessa", description: "Gestisce accessi venosi centrali (CVC, PICC) e medicazioni complesse." },
    { id: "3-3", category: "Leadership", description: "Coordina piccoli gruppi di lavoro e pianifica l'assistenza." },
    { id: "3-4", category: "Educazione", description: "Realizza interventi di educazione terapeutica al paziente e caregiver." },
    { id: "3-5", category: "Etica Professionale", description: "Affronta dilemmi etici complessi con approccio umanistico." },
    { id: "3-6", category: "Accertamento e Case Management", description: "Il tirocinante deve saper guardare oltre la singola prestazione, inquadrando il paziente nel suo percorso di cura." },
    { id: "3-7", category: "Accertamento e Case Management", description: "Triage Ambulatoriale: Capacità di stratificare la priorità dei pazienti in base alla complessità clinica e non solo all'ordine di arrivo." },
    { id: "3-8", category: "Accertamento e Case Management", description: "Pianificazione Assistenziale: Identificazione dei bisogni di salute specifici per il paziente cronico che afferisce alle branche specialistiche (Cardiologia, Diabetologia, Oncologia)." },
    { id: "3-9", category: "Accertamento e Case Management", description: "Collaborazione Multi-professionale: Interazione proattiva con i medici specialisti e il personale di supporto per l'ottimizzazione del flusso di lavoro." },
    { id: "3-10", category: "Educazione Terapeutica e Counselling", description: "Addestramento del caregiver: Insegnare al paziente o ai familiari la gestione di presidi (es. stomie, cateteri urinari) o la somministrazione di farmaci (es. insulina, eparine)." },
    { id: "3-11", category: "Educazione Terapeutica e Counselling", description: "Promozione della salute: Fornire indicazioni su stili di vita corretti e prevenzione delle complicanze legate alla patologia trattata." },
    { id: "3-12", category: "Competenze Organizzative e Gestionali", description: "Gestione della documentazione: Utilizzo corretto dei sistemi informatici sanitari per la tracciabilità delle prestazioni e la continuità ospedale-territorio." },
  ],
};

export const STUDENTS_BY_YEAR: Record<Year, string[]> = {
  [Year.FIRST]: [
    "BRANCA FRANCESCA",
    "CALO' GIACOMO",
    "CALÒ MIRELLA PIA",
    "CAPUTO MARIA STELLA",
    "CAPUTO ASIA",
    "CARBONE VERONICA",
    "CARLUCCIO CRISTIAN",
    "CHIRIATTI GIADA",
    "CINO FRANCESCA",
    "CIRIOLO VITTORIA",
    "COIA DONATO",
    "COLUCCI CARLOTTA",
    "CONGEDO AURORA",
    "CONTE ALESSIA",
    "CORDELLA LAURA",
    "COSI ROBERTA",
    "CUCINELLI ADRIANA",
    "CUPPONE AURORA",
    "CURSANO CHRISTIAN",
    "DANILUC IRINA",
    "DE PAOLIS BENEDETTA",
    "DE ROSA CLAUDIA",
    "DE SIENA CHIARA FRANCESCA",
    "DE VINCENZIS ILENIA",
    "DEI MONTEDURI DE NIGRIS FATIMA",
    "DELL'ANNA ALICE",
    "DI MURO GIORGIA",
    "ELIA MARIKA",
    "ERROI MANUELA",
    "FERNANDEZ SUSEL",
    "FIORITO BEATRICE",
    "GALATI DALILA",
    "GATTO ELEONORA",
    "GIANGRECO SARA",
    "GIANNONE NICOLE",
    "GIANNOTTA MARTA",
    "GIARACUNI LORENZO",
    "INVIDIA MARIA CHIARA",
    "IOLE SARA",
    "LECCI GIULIA",
    "LEO GIANMARCO",
    "LIVIELLO SARA",
    "LONGO FEDERICA",
    "MADAGHIELE MARIA",
    "MADARO RAFFAELLA",
    "MAGLIE ANDREA",
    "MARIANO ELISA MARIA",
    "MARRA ALICE FRANCESCA",
    "MARTELLA ANTONIO",
    "MASELLI VALERIA",
    "MASTROLEO MARTINA",
    "MAURO DONATO",
    "MELE AURORA ALESSANDRA",
    "MIGLIETTA FRANCESCA",
    "MISCIALI ALESSIA MARIA",
    "MORLEO MARIA LUCIA",
    "MOSCAGIURI MAURO",
    "MOSCARA BENEDETTA",
    "MUSCELLA ANDREA",
    "MY GIULIO",
    "NAZZARIO MARTINA",
    "NEGRO MARTINA",
    "NICOLARDI MATTEO",
    "NUZZACHI DAVIDE",
    "NUZZO SOPHIA",
    "ORUMA GLORIA NANJALA",
    "PALADINI ELISA",
    "PALADINI CATERINA",
    "PALMA GIULIA",
    "PARROTTO CARLOTTA",
    "PASTORE MARTINA",
    "PELUSO ASIA",
    "PETRACHI VALENTINA",
    "PRIMICERI GIACOMO",
    "QUARANTA CARLOTTA",
    "ROLLO AURORA",
    "RUSSO ANDREA",
    "SALZANO AURORA",
    "SCARASCIA FRANCESCO",
    "SCHIRINZI ALBERTO",
    "SERIO ALESSANDRO",
    "SPEDICATO LUDOVICA ANTONIA",
    "TENUZZO GRETA",
    "VADRUCCI ILARIA GRAZIA",
    "VALENTE SOFIA",
    "VALGUARNERA SARA MARIA",
    "VANTAGGIATO SERENA",
    "VANTAGGIATO GIULIA",
    "ZAMINGA ALESSIA",
    "SERRA MARTA",
    "VALENTINO SILVIA",
    "TONDO MARTINA",
    "AMALANATHAN MARY AMALA NIROJINI",
    "CONSO CIRO ALESSIO",
    "MITA GRETA",
    "RIZZO LARA",
    "PUCE DESIREE",
    "ESPOSITO MICHELA PIA"
  ],
  [Year.SECOND]: [
    "ALEMANNO CLELIA",
    "ARDITO MATTIA",
    "BIANCO ROSA",
    "BUFFO EMANUELA",
    "CALDARARO SALVATORE",
    "CARBONE MARIAPIA",
    "CARROZZO REBECCA",
    "CARROZZO LAURA",
    "CAZZATO SIMONE",
    "CICCARDI MARIA GRAZIA",
    "COLACI MARTINA",
    "COLACI FEDERICO",
    "COLÌ GRETA",
    "COLUCCIA SILVIA",
    "COLUCCIA FRANCESCA",
    "CONTE VALENTINA",
    "CORCIULO FEDERICA",
    "CUCURACHI MARINA",
    "D'AMATO DAVIDE",
    "D'ARIA GIULIA",
    "D'AURELIO ALICE",
    "DE CATALDIS CHIARA G.",
    "DE FRANCESCO BIANCA TERES",
    "DI GLORIA ILARIA",
    "DINOI NOEMI",
    "DITO VERONICA",
    "FANIGLIULO GIULIA",
    "GHERASIM OANA ANAREEA",
    "GIANNICO SERENA",
    "GIANNONE FRANCESCO",
    "GIANNOTTA MARIA N.",
    "GRECO SIMONA",
    "GRECO GIORGIA",
    "HYSA ALBANA",
    "INGROSSO ELISA",
    "INGROSSO AURORA",
    "KWITCHEU NDJONDJI",
    "SANDIE GERALDINE",
    "LIGUORI GABRIEL",
    "LONGO ALESSIA",
    "LONGO SERENA",
    "LUCATELLI VALENTINA",
    "MACRÌ EUGENIO",
    "MALAGNINO MATTEO",
    "MALERBA GIULIA",
    "MANNARA BEATRICE M.",
    "MARIANO REBECCA RITA",
    "MARTELLA ALBERTO",
    "MARTIRE ALESSIA",
    "MARTIRE DANIELE",
    "MARZO NOEMI",
    "MELE RAFFAELE",
    "MELELEO NICOLE",
    "MELLONE SWAMI",
    "MERICO MATTEO",
    "MEROLA GIUSEPPE",
    "MIGLIACCIO MICHELA",
    "MIGLIETTA CHIARA",
    "MILANESE ANDREA",
    "MILELLO LETIZIA",
    "MONTAGNA ANNA LUCIA",
    "MONTINARO GIULIA",
    "MUSARAJ MAJRA",
    "NORMANNO ELENA",
    "ORTIS MARCO",
    "PALMA ALESSIA",
    "PALMA COSIMO GIOVANNI",
    "PANICO MARTA",
    "PAPADIA GIULIA",
    "PELLEGRINO FEDERICA",
    "PERROTTA DANIEL A.",
    "PIERRI MARCO S.",
    "PIZZOLANTE HELENA",
    "PONZETTA VITO",
    "QUARTA CATERINA",
    "RAGGIO BENEDETTA",
    "RAMBALDI STELLA",
    "RIZZO STEFANIA",
    "RIZZO ALESSIA",
    "ROMANO REBECCA",
    "ROSA RICCARDO",
    "RUGGERI NICCOLO'",
    "RUGGIERO CLARISSA",
    "RUSSO REBECCA",
    "SCARCELLA LORENZO",
    "STEFANIZZI FABRIZIO",
    "STEFANO SOFIA",
    "STELLA CHIARA",
    "STRAFELLA SIMONA",
    "SUDOSI JUANA",
    "TOMA MICHELE",
    "TOMA MARTINA",
    "TRANE SARA",
    "TUNNO ANNALISA",
    "TURCO MARTA",
    "VIVA NICOLE",
    "DE IACO BENEDETTA"
  ],
  [Year.THIRD]: [
    "D'AMBLE MICHELA",
    "BALDASSARRE GIORGIA MA",
    "ANTONAZZO ILARIA",
    "CORNACCHIA FRANCESCA",
    "CASTRI DONATO",
    "CHITTANI MIRIAM",
    "BALDASSARRE MARIKA",
    "BERTOLINI LETIZIA",
    "COPPOLA DONATO",
    "CONOCI FRANCESCA ROMAI",
    "ANTONAZZO REBECCA",
    "CINO FABIANA",
    "BUFANO GIORGIA",
    "CAROPPO SERENA",
    "BARONE MARIA AURORA",
    "DANESE BENEDETTA",
    "CORTESE GIORGIA",
    "CARROZZO GAIA",
    "COTA SHIRLEY",
    "BAGLIVO MARIANGELA",
    "CORDELLA YLENIA",
    "CENZENTO MARIACRISTINA",
    "BISANTI ROCCO",
    "BRAMATO MATTEO",
    "BRANCA ANNA",
    "BLEVE ALESSANDRA",
    "BALDASSARRE GIORGIA M.",
    "D'ALESSANDRIS LUCIA A.",
    "D'AQUINO ROBERTA",
    "DE FRANCESCO ELISABETTA",
    "DE GIORGI ALESSANDRO",
    "DE LORENZIS ALESSIA",
    "DE MATTEIS GAIA MARIA",
    "DE NUCCIO ANTONIO",
    "DE SALVO VERONICA",
    "DE VITIS TATIANA",
    "DI DONFRANCESCO GIORGIA",
    "DONGIOVANNI GABRIELE",
    "FERSINO PASQUALE",
    "FRACASSO AURORA",
    "FRASCARO SILVIA",
    "GHERASIM OANA ANDREEA",
    "GIACOVAZZO ANGELICA",
    "GIANNATTASIO GIULIA",
    "GIANNETTA MAURO",
    "GRANDE ILARIA",
    "GUIDA REBECCA",
    "INVIDIA CHIARA",
    "ISACCO ELEONORA",
    "LIONETTO ALESSIO",
    "MANCO ALBERTO",
    "MARENACI PIETRO",
    "MARGARITO MARIKA",
    "MARGIOTTA EMANUELE",
    "MARIANO MARTINA MARIA",
    "MARIELLO CHIARA",
    "MARZO MARIA",
    "MAURO IRIDE",
    "MELLONE CHRISTIN",
    "MERICO GIADA",
    "MICELLO MATTEO",
    "MUCCIO CHIARA",
    "OLIVARES MARTINA ANTON",
    "PAGLIARA GIULIA",
    "PALOMBA GIORGIA GABRIE",
    "PALUMBO DE RAMUNDO TATIANA",
    "PALUMBO GLORIA",
    "PANICO CLAUDIA",
    "PAPERI ANTONIO G.",
    "PERDOMO YENYS",
    "PERRONE AURORA",
    "PICCI ANNA RITA",
    "PINTAUDI VALENTINA",
    "PREITE FRANCESCA",
    "PUSCIO LAVINIA",
    "QUARTA PIERPAOLO",
    "RIZZO ELISA",
    "RIZZO MARTINA",
    "SCARDIA VALENTINA",
    "SCARDINO SOFIA",
    "SCOLOZZI DILETTA",
    "SHIKHOUNI AGNESE",
    "SICILIANO CHIARA",
    "SPERTI EMANUELE",
    "SPORTA CAPUTI ANNA C.",
    "SURDO ANDREA",
    "TARANTINO MICHELE",
    "TUNDO SIMONA",
    "TURI ALICE",
    "URSO GIULIA",
    "URSO MARTINA",
    "VETERE FABIANA",
    "VETRUGNO NICOLE",
    "ZACHEO GIULIO"
  ],
};

export const SYSTEM_INSTRUCTION = `Agisci come un sistema esperto di valutazione per il tirocinio clinico infermieristico. 
Contesto: Utilizza i criteri del Corso di Laurea in Infermieristica dell'Università del Salento e le linee guida della Pia Fondazione Panico per l'aspetto etico-umanistico.
Il tuo compito è analizzare i punteggi (da 1 a 5) assegnati a diverse competenze cliniche e le note del tutor per fornire un feedback strutturato.
Sii rigoroso ma costruttivo. Valorizza l'aspetto umano della cura (care) oltre a quello tecnico (cure).`;
